### ISSUE TITLE
Project License?

### ISSUE THREAD

**Issue by chsienki** [Arksine/usbtv007-android#3]
Hey, thanks for this library! 

I wanted to use some of the code in a personal project I'm working on, but I notice you don't have a license associated with this repo. 

Seems like by default that means it's copyright and I can't use the code. [See SO post here](https://opensource.stackexchange.com/a/1721)

Was that an intentional choice? Or would you consider adding an open source license so I can build off the code? I'd also be happy to contribute back fixes etc, but without an explicit license I'm not sure how that works.

Thanks again for the hard work!

**Comment by Arksine** [comment]
Not intentional, its been quite some time since I have worked with Android.

I just added a GPLv3 license.  Feel free to use it in your project.

**Comment by chsienki** [comment]
Awesome, thanks!
